AWSTemplateFormatVersion: 2010-09-09
Description: Renewal_Appointment_Reminder

Parameters:

  PinpointProjectId:
    Type: String
    Description: Amazon Pinpoint Project ID
  PinpointSegmentId:
    Type: String
    Description: Amazon Pinpoint Segment ID for customer who will receive a newal reminder
  DaysToRemind:
    Type: String
    Description: Number of days before the renewal date    

Resources:

  PinpointUpdateRenewalSegment:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Role: !GetAtt PinpointUpdateRenewalSegmentRole.Arn
      Runtime: python3.8
      Timeout: 60
      Environment:
        Variables:
          PINPOINT_APP_ID: !Ref PinpointProjectId
          SEGMENT_ID: !Ref PinpointSegmentId
          REMINDER_PERIOD: !Ref DaysToRemind
      Code:
        ZipFile: |
          import os
          import boto3
          import json
          from datetime import date
          import datetime

          pinpoint_id = os.environ['PINPOINT_APP_ID']
          reminder_period = int(os.environ['REMINDER_PERIOD'])
          segment_id = os.environ['SEGMENT_ID']
          client = boto3.client('pinpoint')

          def lambda_handler(event, context):
              today = date.today()
              renewal_reminder = today + datetime.timedelta(days=reminder_period)
              renewal_reminder = renewal_reminder.strftime("%Y/%m/%d")
              print("""
              The date today is """ + str(today) + """
              
              Reminder period is set to """ + str(reminder_period) + """
              
              Users whose renewal date is: """ + renewal_reminder + """ will be contacted via the renewal reminder Pinpoint Journey!
              
              Pinpoint Segment Update Response: 
              """ )
                            
              update_segment = client.update_segment(
              ApplicationId=pinpoint_id,
              SegmentId=segment_id,
              WriteSegmentRequest={
                  'Dimensions': {
                      'UserAttributes': {
                          'renewal_date': {
                              'AttributeType': 'CONTAINS',
                              'Values': [
                                  renewal_reminder,
                              ]
                          }
                      }
                      }
              })              
              print(update_segment['SegmentResponse'])
              print("")

  PinpointUpdateRenewalSegmentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
              -
                Effect: "Allow"
                Action:
                  - "mobiletargeting:UpdateSegment"
                Resource:
                  - !Sub "arn:aws:mobiletargeting:${AWS::Region}:${AWS::AccountId}:*"

  CloudWatchInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt PinpointUpdateRenewalSegment.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CloudWatchRenewalReminder.Arn

#### CLOUDWATCH ALARM TRIGGER LAMBDA
##################################

  CloudWatchRenewalReminder:
    Type: AWS::Events::Rule
    Properties:
      Name: "TriggerPinpointRenewalLambda"
      Description: "Invokes the Lambda for Pinpoint renewal reminder use-case"
      State: "ENABLED"
      ScheduleExpression: "rate(1 day)"
      Targets:
        - 
          Arn: !GetAtt PinpointUpdateRenewalSegment.Arn
          Id: CloudWatchPinpointUpdateRenewalSegment
